//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_ReceiptDtl
    {
        public int ReceiptDtlId { get; set; }
        public Nullable<decimal> ReceiptId { get; set; }
        public string MOPCode { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> BalAmount { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
