//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_InvoiceDtl
    {
        public long InvoiceDtlId { get; set; }
        public Nullable<decimal> InvoiceId { get; set; }
        public Nullable<long> Form2Id { get; set; }
        public string IGMReferenceNo { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<long> NumberofBags { get; set; }
        public Nullable<long> NumberofPkgs { get; set; }
        public string NumberofShps { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> ActualDateofArrival { get; set; }
        public Nullable<decimal> AirlineWeight { get; set; }
        public Nullable<decimal> EICIWeight { get; set; }
    }
}
