//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_Receipt
    {
        public decimal ReceiptId { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<long> CourierCoId { get; set; }
        public Nullable<decimal> ServiceTaxAmount { get; set; }
        public string TerminalCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> ReceiptTypeId { get; set; }
        public Nullable<int> ReceiptChargeTypeId { get; set; }
        public Nullable<decimal> GatePassId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string ExportedtoTally { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
