//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_ReceiptChrg
    {
        public decimal ReceiptId { get; set; }
        public Nullable<int> ReceiptChrgType { get; set; }
        public string IGMNumber { get; set; }
        public Nullable<decimal> FacilitationChrgs { get; set; }
        public Nullable<decimal> FacilitationAmt { get; set; }
        public Nullable<decimal> ScreenAirlineChrgs { get; set; }
        public Nullable<decimal> ScreenAirlineAmt { get; set; }
        public Nullable<decimal> ScreenEICIChrgs { get; set; }
        public Nullable<decimal> ScreenEICIAmt { get; set; }
        public Nullable<decimal> CustomCostRcvrChrgs { get; set; }
        public Nullable<decimal> CustomCostRcvrAmt { get; set; }
        public Nullable<decimal> CustomSixtyPayChrgs { get; set; }
        public Nullable<decimal> CustomSixtyPayAmt { get; set; }
        public Nullable<decimal> ServiceTaxChrgs { get; set; }
        public Nullable<decimal> ServiceTaxAmt { get; set; }
        public Nullable<decimal> PrimaryCessChrgs { get; set; }
        public Nullable<decimal> PrimaryCessAmt { get; set; }
        public Nullable<decimal> SecondaryCessChrgs { get; set; }
        public Nullable<decimal> SecondaryCessAmt { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
