//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_LOGGER
    {
        public long Id { get; set; }
        public string logmessage { get; set; }
        public string functionname { get; set; }
        public string classname { get; set; }
        public string userid { get; set; }
        public string fileid { get; set; }
        public Nullable<System.DateTime> loggingdate { get; set; }
        public string logtype { get; set; }
        public string logcategory { get; set; }
        public string recorddata1 { get; set; }
        public string recorddata2 { get; set; }
        public string recorddata3 { get; set; }
        public string recorddata4 { get; set; }
        public string recorddata5 { get; set; }
        public string recorddata6 { get; set; }
        public string recorddata7 { get; set; }
        public string recorddata8 { get; set; }
        public Nullable<decimal> applicationid { get; set; }
        public string IPADDRESS { get; set; }
        public string SESSIONID { get; set; }
    }
}
