//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUC_BOE
    {
        public decimal AucBOEId { get; set; }
        public string AucBOENo { get; set; }
        public Nullable<decimal> AucListId { get; set; }
        public Nullable<System.DateTime> AucBOEDate { get; set; }
        public string BidderName { get; set; }
        public string BidderVATTinNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> AuctionDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VATPerc { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public string TR6ChallanNo { get; set; }
        public Nullable<System.DateTime> TR6ChallanDate { get; set; }
        public Nullable<decimal> DutyAmount { get; set; }
        public Nullable<int> MOPCode { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Status { get; set; }
        public string TerminalCode { get; set; }
        public string FinancialYear { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
