//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUC_AuctionList
    {
        public decimal AucListId { get; set; }
        public string AucListNo { get; set; }
        public Nullable<System.DateTime> AucListDate { get; set; }
        public Nullable<int> AucListTime { get; set; }
        public string TR6ChallanNo { get; set; }
        public Nullable<System.DateTime> TR6ChallanDate { get; set; }
        public Nullable<decimal> DutyAmount { get; set; }
        public Nullable<int> MOPCode { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<int> Notice2RefNo { get; set; }
        public string TerminalCode { get; set; }
        public string FinancialYear { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
