//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUC_SaleList
    {
        public int AucSaleListId { get; set; }
        public Nullable<decimal> AucListId { get; set; }
        public string BidderName { get; set; }
        public string BidderAddr1 { get; set; }
        public string BidderAddr2 { get; set; }
        public string BidderIdNo { get; set; }
        public string BidderPhoneNo { get; set; }
        public string VATTinNo { get; set; }
        public Nullable<System.DateTime> AucSaleListDate { get; set; }
        public string TerminalCode { get; set; }
        public string FinancialYear { get; set; }
        public string MC_Status { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
