//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUC_AuctionListDtl
    {
        public decimal AucListDtlId { get; set; }
        public Nullable<decimal> AucListId { get; set; }
        public Nullable<decimal> OnHoldId { get; set; }
        public string MemoNo { get; set; }
        public string AucStatus { get; set; }
        public string AucRemarks { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public Nullable<int> ItemLotId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
