//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUC_BOEGroup
    {
        public decimal AucGroupId { get; set; }
        public string AucGroupName { get; set; }
        public Nullable<decimal> AucBOEId { get; set; }
        public string AucSaleLotNo { get; set; }
        public Nullable<decimal> FairPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> RateSD { get; set; }
        public Nullable<decimal> BCD { get; set; }
        public Nullable<decimal> CVD { get; set; }
        public Nullable<decimal> Custom { get; set; }
        public Nullable<decimal> AdditonalCDRate { get; set; }
        public Nullable<decimal> AdditiaonlCDAmount { get; set; }
        public Nullable<decimal> TotalDutyRate { get; set; }
        public Nullable<decimal> TotalDuty { get; set; }
        public string AdditionalInfo { get; set; }
        public string Status { get; set; }
        public string TerminalCode { get; set; }
        public string FinancialYear { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
