//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CSB1Dtl
    {
        public decimal CSB1DtlId { get; set; }
        public Nullable<decimal> CSB1ID { get; set; }
        public Nullable<int> CSBType { get; set; }
        public string ThokaNo { get; set; }
        public Nullable<int> NoofBags { get; set; }
        public Nullable<int> NoofPkgs { get; set; }
        public Nullable<int> NoofShps { get; set; }
        public Nullable<decimal> CSBWeight { get; set; }
        public Nullable<decimal> CSBValue { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
