//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_OFLGatePass
    {
        public int OFLGPID { get; set; }
        public int EntryGatePassId { get; set; }
        public string OfficerName { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> NoOfBags { get; set; }
        public Nullable<int> NoofShps { get; set; }
        public Nullable<int> NoofPkgs { get; set; }
        public Nullable<decimal> OFLWeight { get; set; }
        public Nullable<int> CSB3 { get; set; }
        public Nullable<int> CSB4 { get; set; }
        public string OffloadingPersonStaff { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
