//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CSB1
    {
        public decimal CSB1Id { get; set; }
        public string CSB1No { get; set; }
        public Nullable<System.DateTime> CSB1Date { get; set; }
        public Nullable<int> CSB1Time { get; set; }
        public Nullable<decimal> CourierCoId { get; set; }
        public string ThokaNo { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> DateofDeparture { get; set; }
        public Nullable<int> TimeofDeparture { get; set; }
        public Nullable<System.DateTime> ExpectedDateofLanding { get; set; }
        public string ECMReferenceDocNo { get; set; }
        public Nullable<System.DateTime> ECMReferenceDocDate { get; set; }
        public Nullable<decimal> ECMReferenceDocManifestWt { get; set; }
        public string ECMReferenceNonDocNo { get; set; }
        public Nullable<System.DateTime> ECMReferenceNonDocDate { get; set; }
        public Nullable<decimal> ECMReferenceNonDocManifestWt { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<decimal> InvoiceID { get; set; }
        public Nullable<decimal> ReleaseGatePassID { get; set; }
        public string RelGpClosour { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
