//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CSB1WeightAcceptanceDtl
    {
        public decimal CSB1WADtlId { get; set; }
        public Nullable<decimal> CSB1WAId { get; set; }
        public Nullable<int> NoofBags { get; set; }
        public string UOMCode { get; set; }
        public Nullable<decimal> WAWeight { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
