//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CSB1WeightAcceptance
    {
        public decimal CSB1WAId { get; set; }
        public Nullable<decimal> CSB1Id { get; set; }
        public string UOMCode { get; set; }
        public string WeightRecordedBy { get; set; }
        public string AirlineEmpID { get; set; }
        public string LEOIssuedBy { get; set; }
        public string CourierRepresentativeName { get; set; }
        public Nullable<int> FirstBagRecordTm { get; set; }
        public Nullable<int> LastBagRecordTm { get; set; }
        public string OBCName { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
