//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ReleasePass
    {
        public decimal ReleasePassId { get; set; }
        public Nullable<decimal> CSB1Id { get; set; }
        public string ReleasePassNo { get; set; }
        public Nullable<System.DateTime> ReleasePassDate { get; set; }
        public Nullable<int> ReleasePassTime { get; set; }
        public string AirlineStaff { get; set; }
        public string HandlingStaff { get; set; }
        public string CourierCoStaff { get; set; }
        public string EICIRepresentative { get; set; }
        public string Remarks { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
