//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form2Arrived
    {
        public decimal Form2ID { get; set; }
        public Nullable<int> Form2Type { get; set; }
        public string IGMReferenceNo { get; set; }
        public Nullable<System.DateTime> IGMReferenceDate { get; set; }
        public string ECMReferenceNo { get; set; }
        public Nullable<System.DateTime> ECMReferenceDate { get; set; }
        public Nullable<int> NumberofBags { get; set; }
        public Nullable<int> NumberofPkgs { get; set; }
        public Nullable<int> NumberofShps { get; set; }
        public Nullable<decimal> WeightofShps { get; set; }
        public Nullable<int> NumberofShpsTrans { get; set; }
        public Nullable<int> NumberofPkgsTrans { get; set; }
        public Nullable<decimal> WeightofTrans { get; set; }
    }
}
