//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatePassIssued
    {
        public decimal GatePassId { get; set; }
        public Nullable<decimal> Form2Id { get; set; }
        public Nullable<int> Form2Type { get; set; }
        public string ECMReferenceNo { get; set; }
        public Nullable<int> GPNoofBags { get; set; }
        public Nullable<int> GPNoofPkgs { get; set; }
        public Nullable<int> GPNoofShipments { get; set; }
        public Nullable<decimal> GPWeight { get; set; }
    }
}
