//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_LOV
    {
        public string LOV_ID { get; set; }
        public string SQL_STATEMENT { get; set; }
        public string XML_HEADER { get; set; }
        public string LOVModuleID { get; set; }
        public string CULTURE { get; set; }
    }
}
