//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_GatePassDtl
    {
        public decimal GatePassDtlID { get; set; }
        public Nullable<decimal> GatePassID { get; set; }
        public Nullable<int> Form2Type { get; set; }
        public string ThokaNo { get; set; }
        public Nullable<int> NoofPkgs { get; set; }
        public Nullable<int> NoofBags { get; set; }
        public Nullable<int> NoofShipments { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
