//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_Form2
    {
        public decimal Form2ID { get; set; }
        public string Form2No { get; set; }
        public string IGMReferenceNo { get; set; }
        public Nullable<System.DateTime> IGMReferenceDate { get; set; }
        public string ECMReferenceDocNo { get; set; }
        public Nullable<System.DateTime> ECMReferenceDocDate { get; set; }
        public Nullable<decimal> ECMReferenceDocManifestWt { get; set; }
        public string ECMReferenceNonDocNo { get; set; }
        public Nullable<System.DateTime> ECMReferenceNonDocDate { get; set; }
        public Nullable<decimal> ECMReferenceNonDocManifestWt { get; set; }
        public string ThokaNo { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<long> CourierCoId { get; set; }
        public Nullable<long> AirlineId { get; set; }
        public string FlightNumber { get; set; }
        public string AirportofArrival { get; set; }
        public string AirportofShipment { get; set; }
        public string CountryofExportation { get; set; }
        public Nullable<System.DateTime> ActualDateofArrival { get; set; }
        public Nullable<int> ActualTimeofArrival { get; set; }
        public Nullable<decimal> InvoiceId { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
