//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_OHForwarding
    {
        public decimal ForwardingId { get; set; }
        public string ForwardingNo { get; set; }
        public Nullable<System.DateTime> ForwardingDate { get; set; }
        public Nullable<int> ForwardingTime { get; set; }
        public Nullable<decimal> Form2ID { get; set; }
        public Nullable<decimal> OnHoldId { get; set; }
        public string MemoNo { get; set; }
        public string IGMReferenceNo { get; set; }
        public string ECMReferenceNo { get; set; }
        public string CustomRepresentative { get; set; }
        public string CourierRepresentative { get; set; }
        public string CHARepresentative { get; set; }
        public string ImporterRepresentative { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> InwardWeight { get; set; }
        public string InwardRemarks { get; set; }
        public string InwardCourierRepresentativeName { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string Year { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
