//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_Form1Dtl
    {
        public long Form1DtlId { get; set; }
        public Nullable<long> Form1Id { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<long> CourierCoId { get; set; }
        public string Coloader { get; set; }
        public Nullable<int> NoofBags { get; set; }
        public Nullable<int> NoofPackages { get; set; }
        public Nullable<int> NoofShps { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> ActualNoofBags { get; set; }
        public Nullable<int> ActualNoofPackages { get; set; }
        public Nullable<int> ActualNoofShps { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public string UldNo { get; set; }
        public Nullable<long> InvoiceDtlId { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
