//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_OnHoldMemo
    {
        public decimal OnHoldID { get; set; }
        public string MemoNo { get; set; }
        public Nullable<decimal> Form2ID { get; set; }
        public Nullable<int> Form2Type { get; set; }
        public string IGMReferenceNo { get; set; }
        public string ECMReferenceNo { get; set; }
        public string HAWBNo { get; set; }
        public Nullable<int> NoofPkgs { get; set; }
        public Nullable<int> NoofShps { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string ImportExportCode { get; set; }
        public string IECSourceCode { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<int> OnHoldReason { get; set; }
        public string ReasonDescription { get; set; }
        public string WarehouseLocation { get; set; }
        public string WarehouseRemarks { get; set; }
        public string WarehouseIdentification { get; set; }
        public string CourierStaffName { get; set; }
        public string CourierStaffRemarks { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneePin { get; set; }
        public Nullable<int> OnHoldTypeId { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public string MemoUpdatedBy { get; set; }
        public Nullable<System.DateTime> MemoUpdatedOn { get; set; }
        public string TerminalCode { get; set; }
        public string FinYear { get; set; }
        public string ConsigneeName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> OnHoldDate { get; set; }
        public Nullable<long> OnHoldTime { get; set; }
        public string AucDescription { get; set; }
        public Nullable<decimal> AssessedValue1 { get; set; }
        public Nullable<decimal> AssessedValue2 { get; set; }
        public string AssessedValue1Type { get; set; }
        public string AssessedValue2Type { get; set; }
        public string ConsigneeEmailId { get; set; }
        public string ConsigneeContactNo { get; set; }
        public Nullable<decimal> AucListId { get; set; }
        public Nullable<System.DateTime> Notification1SentOn { get; set; }
        public Nullable<System.DateTime> Notification2SentOn { get; set; }
        public string Notification1SentRemarks { get; set; }
        public string Notification2SentRemarks { get; set; }
        public string DRGroup { get; set; }
        public string ReasonType { get; set; }
        public string ThokaNo { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
