//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_OHTGPGatePass
    {
        public decimal OHTGPGatePassId { get; set; }
        public string OHTGPGatePassNo { get; set; }
        public Nullable<System.DateTime> OHTGPGatePassDate { get; set; }
        public Nullable<long> OHTGPTime { get; set; }
        public Nullable<decimal> Form2ID { get; set; }
        public Nullable<decimal> OnHoldID { get; set; }
        public string MemoNo { get; set; }
        public string IGMReferenceNo { get; set; }
        public string ECMReferenceNo { get; set; }
        public Nullable<int> OHTGPNoOfPks { get; set; }
        public Nullable<int> OHTGPInwardNoOfPks { get; set; }
        public Nullable<decimal> OHTGPWeight { get; set; }
        public Nullable<decimal> OHTGPInwardWeight { get; set; }
        public Nullable<System.DateTime> OHTGPIssueDateTime { get; set; }
        public string PreventiveOfficer { get; set; }
        public Nullable<long> ClearedBy { get; set; }
        public string CHAName { get; set; }
        public Nullable<long> TMPType { get; set; }
        public string GPType { get; set; }
        public string FileNo { get; set; }
        public string OHTGPRemarks { get; set; }
        public string OHTGPInwardRemarks { get; set; }
        public Nullable<decimal> CourierEmpId { get; set; }
        public Nullable<decimal> WaiveDelayCharges { get; set; }
        public Nullable<decimal> DelayedCharges { get; set; }
        public Nullable<decimal> WaiveTDSCharges { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string Year { get; set; }
        public string OHTGPCreatedBy { get; set; }
        public Nullable<System.DateTime> OHTGPCreatedOn { get; set; }
        public string OHTGPInwardCreatedBy { get; set; }
        public Nullable<System.DateTime> OHTGPInwardCreatedOn { get; set; }
        public string OHTGPInwardCourierRepresentativeName { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
