//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_OHGPGatePass
    {
        public decimal OHGPGatePassId { get; set; }
        public string OHGPGatePassNo { get; set; }
        public Nullable<System.DateTime> OHGPGatePassDate { get; set; }
        public Nullable<long> OHGPTime { get; set; }
        public Nullable<decimal> OHGPForm2ID { get; set; }
        public Nullable<decimal> OHGPOnHoldID { get; set; }
        public string OHGPMemoNo { get; set; }
        public string OHGPIGMReferenceNo { get; set; }
        public string OHGPECMReferenceNo { get; set; }
        public Nullable<int> OHGPNoOfPks { get; set; }
        public Nullable<decimal> OHGPWeight { get; set; }
        public Nullable<System.DateTime> OHGPIssueDateTime { get; set; }
        public string OHGPPreventiveOfficer { get; set; }
        public Nullable<long> OHGPClearedBy { get; set; }
        public string OHGPCHAName { get; set; }
        public string OHGPGPType { get; set; }
        public string OHGPFileNo { get; set; }
        public string OHGPDDRNo { get; set; }
        public Nullable<System.DateTime> OHGPDDRDate { get; set; }
        public Nullable<decimal> OHGPDDRAmount { get; set; }
        public string OHGPIDFNumber { get; set; }
        public Nullable<decimal> OHGPAssessedValue { get; set; }
        public string OHGPRemarks { get; set; }
        public Nullable<decimal> OHGPCourierEmpId { get; set; }
        public Nullable<decimal> OHGPWaiveDelayCharges { get; set; }
        public Nullable<decimal> OHGPDelayedCharges { get; set; }
        public Nullable<decimal> OHGPWaiveTDSCharges { get; set; }
        public Nullable<decimal> OHGPServiceTax { get; set; }
        public Nullable<decimal> RedemptionFees { get; set; }
        public Nullable<decimal> PersonalPenalty { get; set; }
        public string ThokaNumber { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public string ChaName { get; set; }
        public Nullable<decimal> TDSPrc { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public string TerminalCode { get; set; }
        public string OHGPStatus { get; set; }
        public string Year { get; set; }
        public string OHGPCreatedBy { get; set; }
        public Nullable<System.DateTime> OHGPCreatedOn { get; set; }
        public string OHGPLastUpDtBy { get; set; }
        public Nullable<System.DateTime> OHGPLastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<decimal> ServiceTaxPerc { get; set; }
        public Nullable<decimal> SwachhBharatCessAmt { get; set; }
        public Nullable<decimal> SwachhBharatCessPerc { get; set; }
    }
}
