//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_Form1
    {
        public long Form1Id { get; set; }
        public string Form1No { get; set; }
        public string FlightNumber { get; set; }
        public string AirportOfShipment { get; set; }
        public string IgmNo { get; set; }
        public Nullable<int> ProvisionalIGMNo { get; set; }
        public Nullable<System.DateTime> IgmDate { get; set; }
        public Nullable<int> TimeOfArrival { get; set; }
        public Nullable<System.DateTime> DateOfArrival { get; set; }
        public string SupervisorName { get; set; }
        public string SecurityOfficer { get; set; }
        public string AirlineEmpName { get; set; }
        public string CustomOfficer { get; set; }
        public string DutyOfficer { get; set; }
        public string CourierRepresentative { get; set; }
        public string FinYear { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
    }
}
