//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_GatePass
    {
        public decimal GatePassId { get; set; }
        public string GatePassNo { get; set; }
        public Nullable<System.DateTime> GatePassDate { get; set; }
        public Nullable<long> Time { get; set; }
        public Nullable<decimal> Form2ID { get; set; }
        public Nullable<decimal> OnHoldID { get; set; }
        public string MemoNo { get; set; }
        public string IGMReferenceNo { get; set; }
        public string ECMReferenceNo { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
        public string PreventiveOfficer { get; set; }
        public string ClearedBy { get; set; }
        public string CHAName { get; set; }
        public string FinYear { get; set; }
        public string GPType { get; set; }
        public string FileNo { get; set; }
        public string DDRNo { get; set; }
        public Nullable<System.DateTime> DDRDate { get; set; }
        public Nullable<decimal> DDRAmount { get; set; }
        public string IDFNumber { get; set; }
        public Nullable<decimal> AssessedValue { get; set; }
        public Nullable<decimal> DutyFeeAmount { get; set; }
        public string Remarks { get; set; }
        public string ChargesApplicable { get; set; }
        public string ChargesApplicableRemarks { get; set; }
        public Nullable<decimal> CourierEmpId { get; set; }
        public Nullable<decimal> WaiveDelayCharges { get; set; }
        public Nullable<decimal> DelayedCharges { get; set; }
        public Nullable<decimal> WaiveTDSCharges { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> RedemptionFine { get; set; }
        public Nullable<decimal> Personalpenalty { get; set; }
        public Nullable<int> DelayDays { get; set; }
        public Nullable<int> TPCTM { get; set; }
        public Nullable<decimal> TDSPrc { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<decimal> ServiceTaxPerc { get; set; }
        public Nullable<decimal> SwachhBharatCessAmt { get; set; }
        public Nullable<decimal> SwachhBharatCessPerc { get; set; }
    }
}
