//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Airline_Dtl
    {
        public int AirlineDtlId { get; set; }
        public int AirlineId { get; set; }
        public string AirlineCode { get; set; }
        public string AirlineName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public string ContactEmail { get; set; }
        public string AirlineAddress1 { get; set; }
        public string AirlineAddress2 { get; set; }
        public string XRayApplicable { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
