//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Courier_MST
    {
        public long CourierCoId { get; set; }
        public string CourierCoCode { get; set; }
        public string CourierCoRegistrationNumber { get; set; }
        public Nullable<System.DateTime> CourierCoRegistrationExpiryDt { get; set; }
        public string CourierCoName { get; set; }
        public string CourierCoTallyName { get; set; }
        public string CourierCoMigratedName { get; set; }
        public string ContactPerson { get; set; }
        public string CourierEmail { get; set; }
        public string CourierContact { get; set; }
        public string CourierCoAddr1 { get; set; }
        public string CourierCoAddr2 { get; set; }
        public string CourierCoState { get; set; }
        public string CourierCoCity { get; set; }
        public Nullable<long> CourierCoPinCode { get; set; }
        public Nullable<int> CourierType { get; set; }
        public Nullable<int> MemberTypeId { get; set; }
        public string TerminalCode { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
