//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CommonMaster_MST
    {
        public int MasterId { get; set; }
        public string MasterDesc { get; set; }
        public string MasterType { get; set; }
        public string MasterValue1 { get; set; }
        public string MasterValue2 { get; set; }
        public string MasterValue3 { get; set; }
        public string MasterValue4 { get; set; }
        public string MasterValue5 { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    }
}
