//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Terminal_MST
    {
        public string TerminalCode { get; set; }
        public string TerminalName { get; set; }
        public string TerminalMode { get; set; }
        public string ROAddress1 { get; set; }
        public string ROAddress2 { get; set; }
        public string ROAddress3 { get; set; }
        public string ROAddress4 { get; set; }
        public string TermAddress1 { get; set; }
        public string TermAddress2 { get; set; }
        public string TermAddress3 { get; set; }
        public string TermAddress4 { get; set; }
        public string ServiceTaxRegnNo { get; set; }
        public string WebSiteName { get; set; }
        public string PanNo { get; set; }
        public Nullable<decimal> ExpFacilitationFee { get; set; }
        public string ExpFacilitationAccount { get; set; }
        public Nullable<decimal> ExpXRayChrgAirline { get; set; }
        public Nullable<decimal> ExpXRayChrgEICI { get; set; }
        public string ExpXRayChrgAccount { get; set; }
        public Nullable<decimal> ExpCustomCostChrg { get; set; }
        public string ExpCustomCostAccount { get; set; }
        public Nullable<decimal> ExpCustomSixtyPayChrg { get; set; }
        public string ExpCustomSixtyPayAccount { get; set; }
        public Nullable<decimal> ImpFacilitationFee { get; set; }
        public string ImpFacilatationAccount { get; set; }
        public Nullable<decimal> ImpCustomCostChrg { get; set; }
        public string ImpCustomCostAccount { get; set; }
        public Nullable<decimal> ImpCustomSixtyPayChrg { get; set; }
        public string ImpCustomSixtyPayAccount { get; set; }
        public Nullable<decimal> ServiceTaxPerc { get; set; }
        public string ServiceTaxAccount { get; set; }
        public Nullable<decimal> PrimaryEduCessPerc { get; set; }
        public Nullable<decimal> SecondaryEduCessPerc { get; set; }
        public string MemberShipFeesAccount { get; set; }
        public string UserAccessFeesAccount { get; set; }
        public string ExportCashAccount { get; set; }
        public string ExportTDSAccount { get; set; }
        public string ImportCashAccount { get; set; }
        public string ImportTDSAccount { get; set; }
        public string FacilitationBankCreditAccount { get; set; }
        public string DetentionFeesAccount { get; set; }
        public string DetentionBankCreditAccount { get; set; }
        public string DetentionCashAccount { get; set; }
        public string DetentionTDSAccount { get; set; }
        public string DetentionServiceTaxAccount { get; set; }
        public string SaleLotAutoMode { get; set; }
        public string ReportPreview { get; set; }
        public string OperationalManager { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public string InvoiceNote { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<decimal> SwachhBharatCess { get; set; }
        public Nullable<decimal> ImportChargesPerc { get; set; }
        public string ImportChargesAccount { get; set; }
        public string ImportChargesName { get; set; }
        public Nullable<decimal> ExportChargesPerc { get; set; }
        public string ExportChargesAccount { get; set; }
        public string ExportChargesName { get; set; }
    }
}
