//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSBM_HST
    {
        public long MSBM_ID { get; set; }
        public string MSBM_NUMBER { get; set; }
        public string NAME_OF_CURRIER { get; set; }
        public Nullable<long> PKGS { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<long> UB_NO { get; set; }
        public Nullable<long> Pkg_Id { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
        public string LastUpDtBy { get; set; }
    }
}
