//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSG_GENERATOR_TEMP
    {
        public long Message_Id { get; set; }
        public Nullable<long> Alert_Id { get; set; }
        public string Attachment_Name { get; set; }
        public string Message_Text_Data { get; set; }
        public string Subject_Text_Data { get; set; }
        public string TO_Id { get; set; }
        public string TO_Group { get; set; }
        public string CC { get; set; }
        public string CC_Group { get; set; }
        public string BCC { get; set; }
        public string BCC_Group { get; set; }
        public string From_Id { get; set; }
        public System.DateTime Submit_Date { get; set; }
        public Nullable<System.DateTime> Do_Not_Send_Date { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
