//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSG_HISTORY_LOGS
    {
        public long MESSAGE_ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string MESSAGE_BODY { get; set; }
        public Nullable<System.DateTime> SENT_TIME { get; set; }
        public Nullable<System.DateTime> RECEIVED_TIME { get; set; }
        public Nullable<long> ALERT_ID { get; set; }
        public Nullable<System.DateTime> RUNTIME { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string CC_VALUE { get; set; }
        public string BCC_VALUE { get; set; }
        public string REPLY_TO { get; set; }
        public string SOURCE_EMAILID { get; set; }
        public string MESSAGE_SUBJECT { get; set; }
        public string ATTACHMENT { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string DELIVERY_STATUS { get; set; }
        public Nullable<long> RELATION_ID { get; set; }
        public string DISPLAY_SENDER_NAME { get; set; }
        public string LOGTYPE { get; set; }
        public string STATUS { get; set; }
        public string REMARKS { get; set; }
    }
}
