//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSG_RELATION
    {
        public long Relation_Id { get; set; }
        public long Alert_Id { get; set; }
        public long Template_Id { get; set; }
    
        public virtual VMSG_ALERT_M VMSG_ALERT_M { get; set; }
        public virtual VMSG_TEMPLATE_M VMSG_TEMPLATE_M { get; set; }
    }
}
