//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMSG_ALERT_M
    {
        public VMSG_ALERT_M()
        {
            this.VMSG_RELATION = new HashSet<VMSG_RELATION>();
        }
    
        public long ALERT_ID { get; set; }
        public string ALERT_DESC { get; set; }
        public Nullable<byte> ALERT_PRIORITY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string Send_Type { get; set; }
        public Nullable<int> DISCLAIMER_ID { get; set; }
        public string ATTACHMENT { get; set; }
        public string SOURCEEMAIL { get; set; }
        public string TO_ID { get; set; }
        public string TO_GROUP { get; set; }
        public string CC { get; set; }
        public string CC_GROUP { get; set; }
        public string BCC { get; set; }
        public string BCC_GROUP { get; set; }
        public string DO_NOT_SEND_DAY { get; set; }
        public string MESSAGE_SUBJECT { get; set; }
        public string BODY_AS_ATTACHMENT { get; set; }
        public string ATTACHMENT_NAME { get; set; }
        public string BODY_MESSAGE_TEXT { get; set; }
        public string AttachmentBaseFolder { get; set; }
        public string SENSITIVITY { get; set; }
        public Nullable<int> SEND_PICK_DAY { get; set; }
        public Nullable<int> SEND_PICK_HOUR { get; set; }
        public string DISPLAY_SENDER_NAME { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<VMSG_RELATION> VMSG_RELATION { get; set; }
    }
}
