//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRCF_TABLE_DTL
    {
        public int TableID { get; set; }
        public Nullable<int> FUNCTIONID { get; set; }
        public string AUTOAUTHORFLAG { get; set; }
        public string TABLE_NAME_TMP { get; set; }
        public string TABLE_NAME_MST { get; set; }
        public string TABLE_NAME_HST { get; set; }
        public string PAGE_HEADER { get; set; }
        public string LIST_TEMP_HEADER { get; set; }
        public string LIST_MST_HEADER { get; set; }
        public string LIST_HST_HEADER { get; set; }
        public string SORTCOL_DEFAULT { get; set; }
        public string PAGINATION_FLAG { get; set; }
        public Nullable<int> PAGE_SIZE { get; set; }
        public string PG_SIZE_DROPDOWN { get; set; }
        public string CREATEDBY_COLNM { get; set; }
        public string CREATEDDT_COLNM { get; set; }
        public string AUTHBY_COLNM { get; set; }
        public string AUTHDT_COLNM { get; set; }
        public string STATUS_COLNM { get; set; }
        public string MC_STATUS_COLNM { get; set; }
        public string DATE_LAST_UPDATED { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string SCHEMA { get; set; }
        public string WHERE_CLAUSE { get; set; }
        public string MAKER_BEFORE_SAVE { get; set; }
        public string MAKER_CUSTOM_SAVE { get; set; }
        public string AUTHOR_BEFORE_SAVE { get; set; }
        public string AUTHOR_AFTER_SAVE { get; set; }
        public string HEADER_COL_WIDTH { get; set; }
        public string BUTTON_LABEL { get; set; }
        public string BUTTON_ACTION { get; set; }
        public string SAVE_URL { get; set; }
        public string SAVE_WINDOWFLAG { get; set; }
        public string SAVE_SUBMITFLAG { get; set; }
        public string PAGE_URL { get; set; }
        public string PAGE_URL_LABEL { get; set; }
        public string PAGE_URL_ACTION { get; set; }
        public string PAGE_URL_WINDOW_FLAG { get; set; }
        public string EXPORT_OPTION { get; set; }
        public string SAVE_TYPE { get; set; }
        public string SAVE_PROC_NAME { get; set; }
        public string NAMESPACE_CLASS_NAME { get; set; }
        public string DLL_METHOD_NAME { get; set; }
        public string DLL_NAME { get; set; }
        public string JS_FILE_NAME { get; set; }
        public string SUMMARY_FLAG { get; set; }
        public string MAX_COLS_SUMMARY { get; set; }
        public string SUMMARY_COL_WIDTH { get; set; }
        public Nullable<int> TABLE_HEIGHT { get; set; }
        public string MASTER_PAGE_NAME { get; set; }
        public string XLSX_EXPORT_FLAG { get; set; }
        public string XLSX_CHECKSUM_FLAG { get; set; }
        public string XLSX_PROTECTION_FLAG { get; set; }
        public string PER_DELETE_FLAG { get; set; }
        public string BULK_UPDATE_COL { get; set; }
        public string EDIT_FLAG { get; set; }
        public string DELETE_FLAG { get; set; }
        public string ADDTAB_FLAG { get; set; }
        public string SELECT_ALL { get; set; }
        public string COMBO_CONTROL_FLAG { get; set; }
        public string TRANSACTION_FLAG { get; set; }
        public string SCREENTYPE { get; set; }
        public string CUSTOM_SAVE_MSG { get; set; }
        public string DEFAULT_SEARCH { get; set; }
        public string DEBUG_FLAG { get; set; }
        public string SPECIAL_CHAR { get; set; }
        public string EXCEL_WORKSHEET_GENBY { get; set; }
        public string SHOW_COPY { get; set; }
        public string MODULEID { get; set; }
        public string COUNTRY_ID { get; set; }
        public string MAX_NO_COLS_HEADER { get; set; }
        public string PRINT_EXPORT_FLAG { get; set; }
        public string PAGE_LINK_LABLE { get; set; }
        public string POPUP_WINDOW_PROPERTY { get; set; }
        public string POPUP_WINDOW_VALUES { get; set; }
        public string WINDOWS_EXIT_OPTION { get; set; }
    }
}
