//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRCF_JSCRIPT_DTL
    {
        public int TABLEID { get; set; }
        public int SCRIPTID { get; set; }
        public Nullable<int> COL_ID { get; set; }
        public string EVENT { get; set; }
        public string CODE { get; set; }
    }
}
