//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRCF_XLSX_STYLE
    {
        public string STYLENAME { get; set; }
        public string FONTNAME { get; set; }
        public int FONTSIZE { get; set; }
        public string FONTCOLOR { get; set; }
        public string ISBOLD { get; set; }
        public string FILLCOLOR { get; set; }
    }
}
