//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRCF_COLUMN_DTL
    {
        public int TABLEID { get; set; }
        public int COL_ID { get; set; }
        public string DBCOL_NAME { get; set; }
        public string DB_REFCOL_FLG { get; set; }
        public string DB_REFCOL_SQL { get; set; }
        public string SHOW_HDR { get; set; }
        public string SHOW_HDR_LABEL { get; set; }
        public string SHOW_HDR_ROWNO { get; set; }
        public string SHOW_HDR_COLUMNSEQ { get; set; }
        public string SHOW_HDR_LABEL_WIDTH { get; set; }
        public string SHOW_HDR_CONTROL_WIDTH { get; set; }
        public string SHOW_HDR_ROW_SPAN { get; set; }
        public string SHOW_HDR_COL_SPAN { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string CONTROL_ADDITIONAL_Message { get; set; }
        public Nullable<int> SQL_ID { get; set; }
        public string DISPLAY_PROPERTY { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<int> DATALENGTH { get; set; }
        public string REQUIRED_FLAG { get; set; }
        public string PK_FLAG { get; set; }
        public string UNIQUE_FLAG { get; set; }
        public string SEQ_FLAG { get; set; }
        public string SEQ_NAME { get; set; }
        public string DEFAULT_VAL { get; set; }
        public string INSERT_FLAG { get; set; }
        public string UPDATE_FLG { get; set; }
        public string SEARCH_FLG { get; set; }
        public string T_UPPER { get; set; }
        public string SHOW_LIST { get; set; }
        public Nullable<int> SHOW_LIST_SEQ { get; set; }
        public Nullable<int> SHOW_LIST_COL_WIDTH { get; set; }
        public string SHOW_LIST_LABEL { get; set; }
        public string SHOW_LIST_COL_ALIGN { get; set; }
        public string SHOW_LIST_HEAD_ALIGN { get; set; }
        public string SORT_FLAG { get; set; }
        public string SORT_EXPRESSION { get; set; }
        public string COLUMN_URL { get; set; }
        public string SEND_PARAMETER { get; set; }
        public string COLUMN_COLUMNAME { get; set; }
        public string XML_PARAM_SEND { get; set; }
        public string RANGE_FLAG { get; set; }
        public Nullable<int> RANGE_VAL_COL_ID { get; set; }
        public string DB_COL_FLAG { get; set; }
        public string COLUMN_VALUE_SQL { get; set; }
        public string JS_FUNCTION { get; set; }
        public string SUMFLAG { get; set; }
        public Nullable<int> COLUMN_PERSESION { get; set; }
        public string ENCRYPTION_FLAG { get; set; }
        public string SESSION_VALUE { get; set; }
        public string SESSION_PARAMETER { get; set; }
        public string CUSTOM_SEARCH_FLAG { get; set; }
        public string XLSX_COL_FLAG { get; set; }
        public Nullable<int> XLSX_COLUMN_SEQ { get; set; }
        public string XLSX_HEADER_TEXT { get; set; }
        public string XLSX_HEADER_STYLE_NAME { get; set; }
        public string XLSX_DATA_STYLE_NAME { get; set; }
        public string XLSX_NUM_FORMAT { get; set; }
        public string XLSX_PROTECTION_FLAG { get; set; }
        public string EXPORT_FLAG { get; set; }
        public string EXPORT_COL_LABEL { get; set; }
        public Nullable<int> EXPORT_COL_SEQ { get; set; }
        public string XML_PARAM_FLAG { get; set; }
        public string SQL_DATA_TYPE { get; set; }
        public string SQL_STATEMENT { get; set; }
        public string COMPUTED_COLUMN { get; set; }
        public string COLUMN_COPY { get; set; }
        public string REMARKS { get; set; }
        public string CONTROL_ADDITIONAL_INFORMATION { get; set; }
        public string SHOW_HDR_COL_NO { get; set; }
        public string POPUP_WINDOW_PROPERTY { get; set; }
        public string POPUP_WINDOW_VALUES { get; set; }
        public string ADD_SHOW_HDR_ROWNO { get; set; }
        public string ADD_SHOW_HDR_COLUMNSEQ { get; set; }
        public string ADD_SHOW_HDR_ROW_SPAN { get; set; }
        public string ADD_SHOW_HDR_COL_SPAN { get; set; }
        public string ADD_DISPLAY_PROPERTY { get; set; }
        public string ADD_REQUIRED_FLAG { get; set; }
        public string ADD_SHOW_HDR { get; set; }
    }
}
