//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRCF_DEBUG_DTL
    {
        public Nullable<int> TABLE_ID { get; set; }
        public Nullable<System.DateTime> DEBUG_DATE { get; set; }
        public string PROC_NAME { get; set; }
        public int SEQUENCE { get; set; }
        public string STEP_STR { get; set; }
        public string SQL_STR { get; set; }
        public Nullable<int> LOG_SEQ { get; set; }
        public string USERID { get; set; }
        public string IPADDRESS { get; set; }
        public string SESSIONID { get; set; }
    }
}
