//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_QUESTION_MST
    {
        public VSEC_QUESTION_MST()
        {
            this.VSEC_LOGIN_MST = new HashSet<VSEC_LOGIN_MST>();
            this.VSEC_LOGIN_MST1 = new HashSet<VSEC_LOGIN_MST>();
            this.VSEC_LOGIN_MST2 = new HashSet<VSEC_LOGIN_MST>();
        }
    
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<VSEC_LOGIN_MST> VSEC_LOGIN_MST { get; set; }
        public virtual ICollection<VSEC_LOGIN_MST> VSEC_LOGIN_MST1 { get; set; }
        public virtual ICollection<VSEC_LOGIN_MST> VSEC_LOGIN_MST2 { get; set; }
    }
}
