//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_LOGIN_MST
    {
        public VSEC_LOGIN_MST()
        {
            this.VSEC_USER_ROLE_MAP = new HashSet<VSEC_USER_ROLE_MAP>();
        }
    
        public long LoginMId { get; set; }
        public Nullable<long> UserMstID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public int ProfileId { get; set; }
        public Nullable<int> QuestionId1 { get; set; }
        public string Answer1 { get; set; }
        public Nullable<int> QuestionId2 { get; set; }
        public string Answer2 { get; set; }
        public Nullable<int> QuestionId3 { get; set; }
        public string Answer3 { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public string LastPassword { get; set; }
        public Nullable<int> PasswordRetry { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual VSEC_PROFILE_MST VSEC_PROFILE_MST { get; set; }
        public virtual VSEC_QUESTION_MST VSEC_QUESTION_MST { get; set; }
        public virtual VSEC_QUESTION_MST VSEC_QUESTION_MST1 { get; set; }
        public virtual VSEC_QUESTION_MST VSEC_QUESTION_MST2 { get; set; }
        public virtual VSEC_USER_MST VSEC_USER_MST { get; set; }
        public virtual ICollection<VSEC_USER_ROLE_MAP> VSEC_USER_ROLE_MAP { get; set; }
    }
}
