//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_APPLICATIONS
    {
        public VSEC_APPLICATIONS()
        {
            this.VSEC_FUNCTION_ACCESS = new HashSet<VSEC_FUNCTION_ACCESS>();
            this.VSEC_FUNCTION_MST = new HashSet<VSEC_FUNCTION_MST>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationPath { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<VSEC_FUNCTION_ACCESS> VSEC_FUNCTION_ACCESS { get; set; }
        public virtual ICollection<VSEC_FUNCTION_MST> VSEC_FUNCTION_MST { get; set; }
    }
}
