//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_ROLE_MST
    {
        public VSEC_ROLE_MST()
        {
            this.VSEC_FUNCTION_ACCESS = new HashSet<VSEC_FUNCTION_ACCESS>();
            this.VSEC_USER_ROLE_MAP = new HashSet<VSEC_USER_ROLE_MAP>();
        }
    
        public int RoleId { get; set; }
        public Nullable<int> ParentRoleId { get; set; }
        public string RoleSName { get; set; }
        public string DisplayName { get; set; }
        public string ActiveFlag { get; set; }
        public string Status { get; set; }
        public string MC_Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string LastUpDtBy { get; set; }
        public Nullable<System.DateTime> LastUpDtOn { get; set; }
    
        public virtual ICollection<VSEC_FUNCTION_ACCESS> VSEC_FUNCTION_ACCESS { get; set; }
        public virtual ICollection<VSEC_USER_ROLE_MAP> VSEC_USER_ROLE_MAP { get; set; }
    }
}
