//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_FUNCTION_ACCESS
    {
        public int FAID { get; set; }
        public int FnID { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> ParentFnID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual VSEC_APPLICATIONS VSEC_APPLICATIONS { get; set; }
        public virtual VSEC_FUNCTION_MST VSEC_FUNCTION_MST { get; set; }
        public virtual VSEC_ROLE_MST VSEC_ROLE_MST { get; set; }
    }
}
