//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_FUNCTION_MST
    {
        public VSEC_FUNCTION_MST()
        {
            this.VSEC_FUNCTION_ACCESS = new HashSet<VSEC_FUNCTION_ACCESS>();
        }
    
        public int FnID { get; set; }
        public string FnDisplay { get; set; }
        public string FnDesc { get; set; }
        public string FnURL { get; set; }
        public Nullable<int> FnParent { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<short> FnSort { get; set; }
        public string IsActive { get; set; }
        public string AppearsInMenu { get; set; }
        public string ShowToAll { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual VSEC_APPLICATIONS VSEC_APPLICATIONS { get; set; }
        public virtual ICollection<VSEC_FUNCTION_ACCESS> VSEC_FUNCTION_ACCESS { get; set; }
    }
}
