//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIAwithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSEC_USER_ROLE_MAP
    {
        public long MapId { get; set; }
        public long LoginMId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual VSEC_LOGIN_MST VSEC_LOGIN_MST { get; set; }
        public virtual VSEC_ROLE_MST VSEC_ROLE_MST { get; set; }
    }
}
